---

- name: Set talosconfig endpoints
  run_once: true
  shell: >
    talosctl config endpoint --talosconfig secrets/talosconfig.yaml
    {% if talos_api_endpoint is defined and talos_api_endpoint %}
      {{ talos_api_endpoint }}
    {% else %}
      {{ groups['all'] | map('extract', hostvars, ['ip']) | map('regex_replace', '/.+', '') | join(' ') }}
    {% endif %}
  args:
    chdir: "{{ inventory_dir }}/clusters/{{ cluster_name }}"
  changed_when: false
