---

- include_tasks: check.yaml
  tags:
    - check

- include_tasks: secretstats.yaml
  when: >
    (apply_configs is defined and apply_configs == "true") or
    (get_secrets_stats is defined and get_secrets_stats == "true")
  tags:
    - secretstats

- include_tasks: prepare.yaml
  when: apply_configs is defined and apply_configs == "true"
  tags:
    - prepare

- include_tasks: generate.yaml
  when: apply_configs is defined and apply_configs == "true"
  tags:
    - generate

- include_tasks: patch.yaml
  when: apply_configs is defined and apply_configs == "true"
  tags:
    - patch

- include_tasks: endpoints.yaml
  when: configure_endpoints is defined and configure_endpoints == "true"
  tags:
    - endpoints

- include_tasks: bootstrap.yaml
  when: bootstrap is defined and bootstrap == "true"
  tags:
    - bootstrap

- include_tasks: kubeconfig.yaml
  when: >
    (bootstrap is defined and bootstrap == "true") or
    (get_kubeconfig is defined and get_kubeconfig == "true")
  tags:
    - kubeconfig

- include_tasks: encrypt.yaml
  when: apply_configs is defined and apply_configs == "true"
  tags:
    - encrypt

- include_tasks: charts.yaml
  when: install_charts is defined and install_charts == "true"
  tags:
    - charts

- include_tasks: upgrade.yaml
  tags:
    - upgrade
