---

- name: Create cluster dir
  run_once: true
  file:
    path: "{{ inventory_dir }}/clusters/{{ cluster_name }}"
    state: directory
    mode: '0755'
  register: cluster_dir

- name: Create cluster dirs
  run_once: true
  file:
    path: "{{ inventory_dir }}/clusters/{{ cluster_name }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - secrets

- name: Decrypt secret data
  run_once: true
  no_log: "{{ not show_log }}"
  shell: >
    ansible-vault decrypt "{{ item.item }}.yaml.enc"
    --output secrets/{{ item.item }}.yaml
    --vault-password-file {{ inventory_dir }}/.vault_pass
    && md5sum secrets/{{ item.item }}.yaml
  args:
    chdir: "{{ inventory_dir }}/clusters/{{ cluster_name }}"
  vars:
    query: "results[?item=='{{ item.item }}'].stat.checksum"
  register: result
  loop: "{{encrypted_stats.results }}"
  when: item.stat.exists == true
  changed_when: >
    (decrypted_stats | json_query(query) | join()) == "" or
    (decrypted_stats | json_query(query) | join()) not in result.stdout
