---

- name: Set default secret list
  run_once: true
  set_fact:
    secrets: "{{ (groups['all'] + default_secrets) }}"
  vars:
    default_secrets:
      - secrets
      - controlplane
      - worker
      - talosconfig

- name: Get decrypted secrets stat
  run_once: true
  stat:
    path: "{{ inventory_dir }}/clusters/{{ cluster_name }}/secrets/{{ item }}.yaml"
    checksum_algorithm: md5
  register: decrypted_stats
  loop: "{{ secrets }}"

- name: Get encrypted secrets stat
  run_once: true
  stat:
    path: "{{ inventory_dir }}/clusters/{{ cluster_name }}/{{ item }}.yaml.enc"
    checksum_algorithm: md5
  register: encrypted_stats
  loop: "{{ secrets }}"

